(defalias 'cfn 'copy-file-name)
(defalias 'cfp 'copy-file-path)
(defalias 'cdf 'copy-file-directory)
(defalias 'ar 'align-regexp)
(defalias 'dl 'delete-matching-lines)
(defalias 'kl 'keep-lines)
(defalias 'rb 'rename-buffer)
(defalias 'ru 'rename-uniquely)
(defalias 'sl 'sort-lines)

(provide 'aliases)
